name: CTF3
version: '${project.version}'
main: darkyiu.me.ctf3.CTF3
api-version: '1.20'
commands:
  kit:
    description: Give yourself a kit!
  join:
    description: Join a round of CTF!
  leave:
    description: Leave a lobby!
  vanish:
    description: Make yourself invisible to others!